### ISSUE TITLE
Take a look at this issue, please

### ISSUE THREAD

**Issue by hwt88** [ashdavies/eternity#8]
I follow your [article](https://medium.com/proandroiddev/dagger-2-android-modules-e168821cfc57) and i have a problem with Dagger2 Android Modules. Help to take a look at this [issue](https://github.com/google/dagger/issues/732)

**Comment by ashdavies** [comment]
@UsherBaby Please ensure you are using the correct support modules, and follow the steps provided in the documentation, you can use the following repo as a reference should you wish.
https://github.com/ashdavies/dagger-sample

**Comment by ceefour** [comment]
@ashdavies Can you extend the sample to use support-v4 Fragment ? I have no problem with AppCompatActivity but error with support Fragment : :(

```
java.lang.IllegalArgumentException: No injector factory bound for Class<com.hendyirawan.geoassistant.SensorFragment>
  at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:104)
  at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:74)
  at com.hendyirawan.geoassistant.SensorFragment.onAttach(SensorFragment.kt:107)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1363)
  at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
  at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
  at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
  at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
  at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
  at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
  at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
```

**Comment by ashdavies** [comment]
@ceefour the sample doesn't use fragments, nor does this project, but Dagger should support framework fragment types, make sure you have a component created for your fragment either manually or with `@ContributesAndroidInjector` and be sure to follow the documentation.
